### ISSUE TITLE
This does not crash my game but, not the less weird error

### ISSUE THREAD

**Issue by 3prm3** [CoolMineman/BitsAndChisels#21] opened 2021-02-26 22:58 UTC
Error executing task on Client
java.lang.NullPointerException
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4)
	at io.github.coolmineman.bitsandchisels.BitsBlockEntity.doQuad(BitsBlockEntity.java:175)
	at io.github.coolmineman.bitsandchisels.BitsBlockEntity.rebuildMesh(BitsBlockEntity.java:268)
	at io.github.coolmineman.bitsandchisels.BitsBlockEntity.fromClientTag(BitsBlockEntity.java:318)
	at net.minecraft.client.network.ClientPlayNetworkHandler.redirect$ced000$deserializeBlockEntityChunkData(ClientPlayNetworkHandler:7487)
	at net.minecraft.client.network.ClientPlayNetworkHandler.onChunkData(ClientPlayNetworkHandler:787)
	at net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.apply(ChunkDataS2CPacket:123)
	at net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket.apply(ChunkDataS2CPacket:23)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
	at net.minecraft.class_2600$$Lambda$9951/340602251.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27

**Comment by CoolMineman** [comment] 2021-03-18 20:52
dupe of #26 fixed in latest release

**Closed by CoolMineman** 2021-03-18 20:52 UTC
