### ISSUE TITLE
Server crash when jumping on chiseled block

### ISSUE THREAD

**Issue by Father-Meat** [CoolMineman/BitsAndChisels#54] opened 2021-05-18 01:41 UTC
Here is the server crash log.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/17/21 3:42 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.class_4970$class_4971.handler$clp001$getCollisionShape(class_4970.java:4067)
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:985)
	at baritone.cd.h(Unknown Source)
	at baritone.cd.c(Unknown Source)
	at baritone.cd.b(Unknown Source)
	at baritone.cd.b(Unknown Source)
	at baritone.h.pathStart(Unknown Source)
	at baritone.h.onTickServer(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at baritone.bx.onTickServer(Unknown Source)
	at baritone.a.serverTick(Unknown Source)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_3222_1356f9d8.tickComponents(Unknown Source)
	at net.minecraft.class_3218.handler$bng000$tick(class_3218.java:7075)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.handler$dcb000$modifiedRunLoop(MinecraftServer.java:10810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_4970$class_4971.handler$clp001$getCollisionShape(class_4970.java:4067)
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:985)
	at baritone.cd.h(Unknown Source)
	at baritone.cd.c(Unknown Source)
	at baritone.cd.b(Unknown Source)
	at baritone.cd.b(Unknown Source)
	at baritone.h.pathStart(Unknown Source)
	at baritone.h.onTickServer(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at baritone.bx.onTickServer(Unknown Source)
	at baritone.a.serverTick(Unknown Source)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_3222_1356f9d8.tickComponents(Unknown Source)
	at net.minecraft.class_3218.handler$bng000$tick(class_3218.java:7075)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 184
	Entity Name: FatherMeat
	Entity's Exact location: -337.09, 63.00, -3805.84
	Entity's Block location: World: (-338,63,-3806), Chunk: (at 14,3,2 in -22,-238; contains blocks -352,0,-3808 to -337,255,-3793), Region: (-1,-8; contains chunks -32,-256 to -1,-225, blocks -512,0,-4096 to -1,255,-3585)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 1 total; [class_3222['FatherMeat'/184, l='ServerWorld minecraft:overworld world', x=-337.09, y=63.00, z=-3805.84]]
	Chunk stats: ServerChunkCache: 2861
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,72,224), Chunk: (at 0,4,0 in 6,14; contains blocks 96,0,224 to 111,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1835905 game time, 854555 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 49936 (now: false), thunder time: 123355 (now: false)
	Known server brands: Fabric/Gunpowder, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.handler$dcb000$modifiedRunLoop(MinecraftServer.java:10810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11876028760 bytes (11325 MB) / 15748562944 bytes (15019 MB) up to 15748562944 bytes (15019 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xmx15360M -Xms15360M
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		aopalliance_aopalliance: aopalliance 1.0
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.9.136
		artifacts: Artifacts 3.2.1+fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automatone: Automatone 0.3.4
		besmirchment: Besmirchment 1.16.5-6
		betterend: Better End 0.9.6-pre
		betternether: Better Nether 5.0.7
		bewitchment: Bewitchment 1.16.5-13
		bigbeacons: Big Beacons 1.1.1
		bitsandchisels: BitsAndChisels 2.1.4
		blue_endless_jankson: jankson 1.2.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.0.2-1.16.5
		byg: BYG 1.1.8
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-item: Cardinal Components API (items) 2.8.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.2
		cardinal-components-world: Cardinal Components API (worlds) 2.8.2
		carpet: Carpet Mod 1.4.35
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.24
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.12.3
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.12.3
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.12.3
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.12.3
		com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.12.3
		com_google_inject_guice: guice 4.2.3
		craftables: Craftables 1.0.0
		croptopia: Croptopia 1.4.0
		curios: Curios API 0.0.13-1.16.5
		dehydration: Dehydration 1.1.4
		dragonloot: DragonLoot 1.0.6
		enderitemod: Enderite Mod 1.2.4
		extraalchemy: Extra Alchemy 1.4.4
		fabric: Fabric API 0.34.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.0+kotlin.1.5.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fabrilousupdater: FabrilousUpdater 1.0.5
		fallflyinglib: FallFlyingLib 1.1.0
		fallingtree: FallingTree 2.11.3
		fasttransferlib: Fast Transfer Lib 0.3.1
		fiber: fiber 0.23.0-2
		geckolib3: Geckolib 3.0.34
		gravestones: Gravestones v1.9
		gunpowder-base: Gunpowder 0.5.5+1.16.5
		gunpowder-currency: Gunpowder Currency 1.0.2+gunpowder.0.3.7.mc.1.16.5
		gunpowder-signshop: Gunpowder Signshop 1.0.2+gunpowder.0.5.4.mc.1.16.5
		haema: Haema 1.7.0
		harvest_scythes: Harvest Scythes 2.0.4
		imm_ptl_core: Immersive Portals Core 0.90
		immersive_portals: Immersive Portals 0.90
		impersonate: Impersonate 2.2.1
		indrev: Industrial Revolution 1.9.11-BETA
		inventorysorter: Inventory Sorter 1.7.9-1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_inject_javax_inject: javax.inject 1
		kyrptconfig: Kytpt Config 1.1.6-1.16
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		lithium: Lithium 0.6.4
		maelstrom_library: Maelstrom Library 1.2-1.16.5
		magna: Magna 0.2.1-1.16.5
		minecraft: Minecraft 1.16.5
		moenchantments: Mo'Enchantments 1.15.0
		multi_item_lib: Multi Item Lib 1.3.0
		multipart_entities: MultipartEntities 1.1.1-SNAPSHOT
		mysql_mysql-connector-java: mysql-connector-java 5.1.46
		netherite_plus: Netherite Plus Mod 1.4.4-1.16.5
		nourish: Nourish 1.2.1
		org_jetbrains_exposed_exposed-core: exposed-core 0.31.1
		org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.31.1
		org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.31.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.0
		org_postgresql_postgresql: postgresql 42.2.2
		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta1
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.28.0
		org_yaml_snakeyaml: snakeyaml 1.26
		oro_config: OroArmor Config 3.0.0
		pandemonium: Requiem: Pandemonium 1.7.6
		pandemoniumapi: Requiem: Pandemonium-API 1.7.6
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 2.1.0+21w18a
		playerabilitylib: Pal 1.2.1
		ratsmischief: Rat's Mischief 1.1.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		reborncore: Reborn Core 4.7.2+build.132
		recipeconditions: Fabric Recipe Conditions 0.4.0
		requiem: Requiem 1.7.6
		requiemapi: Requiem-API 1.7.6
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		somnus: Somnus API 0.0.11-1.16.5
		stacc: Stacc 1.0.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.2+build.220
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.4.3
		things: Things 0.1.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		totemicoverhaul: Totemic Overhaul 1.1.4
		trinkets: Trinkets 2.6.7
		winged: Winged Mod 1.16.5-2.0.5
		wthit: wthit 2.10.0
		xaerominimap: Xaero's Minimap 21.8.1
		xaeroworldmap: Xaero's World Map 1.13.5
		xlpackets: XLPackets 1.1
	Player Count: 1 / 10; [class_3222['FatherMeat'/184, l='ServerWorld minecraft:overworld world', x=-337.09, y=63.00, z=-3805.84]]
	Data Packs: vanilla (incompatible), Fabric Mods, file/multiplayer sleep v2.5.2.zip, file/unlock all recipes v2.0.1.zip
	Is Modded: Definitely; Server brand changed to 'Fabric/Gunpowder'
	Type: Dedicated Server (map_server.txt)

**Comment by CoolMineman** [comment] 2021-05-18 04:16
This is caused by cabaletta/baritone#2148 which is used in this strange automatone mod you have

**Comment by CoolMineman** [comment] 2021-05-19 01:31
fixed in latest automatone

**Closed by CoolMineman** 2021-05-19 01:31 UTC
